Feature/gpx 472
gepaplexx/gp-helm-chart-development pull request #160
Opened 2022-12-01 08:28 UTC by sgartner03

2022-12-01 09:07 UTC, hwirnsberger requested changes

2022-12-01 09:07 UTC, hwirnsberger commented on infra/gp-identity-provider/Chart.yaml
> +version: 1.2.10
warum?

2022-12-02 11:39 UTC, sgartner03 commented on infra/gp-identity-provider/Chart.yaml
> +version: 1.2.10
Irgendwie sind mir die uncommiteten changes vom identity provider hier reingerutscht und ich hab das mit der chart version anscheinend übersehen, werd ich natürlich rückgängig machen

2022-12-06 08:00 UTC, hwirnsberger approved these changes

2022-12-06 14:23 UTC, merged