GPX-503: Helm Chart für den Alertmanager Health Check
gepaplexx/gp-helm-chart-development pull request #186
Opened 2023-01-02 16:04 UTC by sgartner03

Helm Chart für den Alertmanager Health Check Endpoint

2023-01-02 16:31 UTC, ErhardSiegl commented
Wo finde ich die Sourcen für das Image ghcr.io/gepaplexx/alertmanager-health:latest?

2023-01-03 07:42 UTC, Lucostus requested changes

2023-01-03 07:42 UTC, Lucostus commented on infra/gp-alertmanager-health/values.yaml
> +networking:
Im Value File sollte meiner Meinung nach auch so was, wie der Release Namespace definiert sein.

2023-01-03 08:30 UTC, sgartner03 commented on infra/gp-alertmanager-health/values.yaml
> +networking:
Ich re-requeste die review, weil wir uns ja geeinigt haben im Daily, dass das mit {{ .Release.Namespace }} passt. Bezüglich weiteren Values: Ich würde die dann auch erst hinzufügen, wenn wir sie wirklich benötigen

2023-01-03 08:57 UTC, sgartner03 commented
> Wo finde ich die Sourcen für das Image ghcr.io/gepaplexx/alertmanager-health:latest?

Die Sourcen liegen jetzt unter https://github.com/gepaplexx/alertmanager-healthcheck.

 Dort drinnen wird mit einer Action das Image dann in unsere Packages gepusht, das habe ich jetzt dementsprechend in diesem PR neu referenzieren müssen.

2023-01-03 09:14 UTC, ErhardSiegl commented
> > Wo finde ich die Sourcen für das Image ghcr.io/gepaplexx/alertmanager-health:latest?
> 
> Die Sourcen liegen jetzt unter https://github.com/gepaplexx/alertmanager-healthcheck.

Help people interested in this repository understand your project by adding a README. :-) Dann sparst du dir etwas Doku in Confluence. Heißt die Applikation _alertmanager-healthcheck_ oder _alertmanager-health_ ? Besser die Namen konsistent halten.

2023-01-03 12:23 UTC, sgartner03 commented
> > > Wo finde ich die Sourcen für das Image ghcr.io/gepaplexx/alertmanager-health:latest?
> > 
> > 
> > Die Sourcen liegen jetzt unter https://github.com/gepaplexx/alertmanager-healthcheck.
> 
> Help people interested in this repository understand your project by adding a README. :-) Dann sparst du dir etwas Doku in Confluence. Heißt die Applikation _alertmanager-healthcheck_ oder _alertmanager-health_ ? Besser die Namen konsistent halten.

Hab ein README hinzugefügt. 
Hab in gepaplexx/alertmanager-healthcheck, sowie hier den Namen einheitlich auf "alertmanager-healthcheck" gesetzt

2023-01-04 08:52 UTC, ErhardSiegl approved these changes

2023-01-04 09:32 UTC, merged