GPX-567: Actions starten jeden Montag um 07:00
gepaplexx/gp-helm-chart-development pull request #189
Opened 2023-01-10 13:42 UTC by sgartner03

2023-01-10 14:18 UTC, Lucostus approved these changes
LGTM

2023-01-12 08:28 UTC, gattma requested changes

2023-01-12 08:28 UTC, gattma commented on .github/workflows/branch.yaml
> +    - cron: "0 7 * * 1"
Hier wieder entfernen.

2023-01-12 08:28 UTC, gattma commented on .github/workflows/develop.yaml
> +    - cron: "0 7 * * 1"
Hier wieder entfernen.

2023-01-12 08:28 UTC, gattma commented on .github/workflows/main.yaml
> +    - cron: "0 7 * * 1"
Bitte Ausführungszeit anpassen (0 0 * * 1).
Schedule job unten erweitern: if: ${{ github.event_name != 'schedule' }}

2023-01-12 08:28 UTC, gattma commented on .github/workflows/release-development-versions.yaml
> +    - cron: "0 7 * * 1"
Hier wieder entfernen.

2023-01-23 07:24 UTC, gattma approved these changes

2023-01-23 09:08 UTC, merged