GPX-317 added helm chart and configuration for SonarQube installation
gepaplexx/gp-helm-chart-development pull request #26
Opened 2022-05-05 14:36 UTC by fhochleitner

Helm Chart für Installation von Sonarqube. Notwendige Anpassungen und Konfigurationen für OpenShift. 

@hwirnsberger beim JMX Exporter/Prometheus hat's noch was. Da brauch ich glaub ich deine Hilfe :)

2022-05-06 13:33 UTC, hwirnsberger commented
Machen wir das gemeinsam am Mittwoch?

2022-05-10 06:40 UTC, fhochleitner commented
hab das mail mit dem kommentar übersehen und wundere mich die ganze zeit, warum keine rückmeldung kommt. 
yes machen wir!

2022-05-11 08:14 UTC, hwirnsberger requested changes
Bitte die Änderungen einarbeiten.

2022-05-11 08:14 UTC, hwirnsberger commented on bke-development/gp-cicd-sonarqube/templates/sonarqube-scc.yaml
> +{{- if and (.Values.OpenShift.enabled) (.Values.OpenShift.createSCC) }}
bitte entfernen, wir verwenden immer openshift.

2022-05-11 08:14 UTC, hwirnsberger commented on bke-development/gp-cicd-sonarqube/templates/sonarqube-scc.yaml
> +# seLinuxOptions:
bitte kommentare entfernen

2022-05-11 08:14 UTC, hwirnsberger commented on bke-development/gp-cicd-sonarqube/values.yaml
> +  enabled: true
auch hier entfernen

2022-05-11 08:14 UTC, hwirnsberger commented on bke-development/gp-cicd-sonarqube/values.yaml
> +      namespace: "" #askHerbert
anscheinend nicht nötig. der servicemonitor wird im gleichen namespace angelegt und openshift-usermonitoring bekommt das mit und die metriken werden gesammelt

2022-05-11 08:39 UTC, merged