Feature/GPX-668
gepaplexx/gp-helm-chart-development pull request #353
Opened 2023-06-12 10:43 UTC by Lucostus

+ Made system dashboards as optional configurations as multena dashboards will become default
+ Restructured numbers
+ RBAC optional as it will not be used

2023-06-12 10:50 UTC, hwirnsberger requested changes
Bitte noch die Chart Version hochdrehen.
Ich verstehe auch die Nummerierung der Files nicht, kann mir jemand einen Grund dafür nennen?

2023-06-12 10:50 UTC, hwirnsberger commented on infra/gp-grafana-instance/templates/01-grafana-crd.yaml
> +      {{- if .Values.systemDashboards }}
Braucht man überhaupt noch ein env?

2023-06-12 10:57 UTC, Lucostus commented
> Bitte noch die Chart Version hochdrehen. Ich verstehe auch die Nummerierung der Files nicht, kann mir jemand einen Grund dafür nennen?

Damit die Sachen in richtiger rein Folge eingespielt werden.

2023-06-12 11:02 UTC, fhochleitner requested changes

2023-06-12 11:04 UTC, hwirnsberger commented on infra/gp-grafana-instance/templates/01-grafana-crd.yaml
> +      {{- if .Values.systemDashboards }}
Ich glaube man kann das ganze {{- if .Values.systemDashboards }} um env ziehen.

2023-06-12 11:09 UTC, Lucostus commented
@fhochleitner das hat sich auf die File Nummerierung bezogen.

2023-06-12 11:14 UTC, fhochleitner commented
> @fhochleitner das hat sich auf die File Nummerierung bezogen.

ich weiß: that's not how argocd/helm work. at all. aber ich mag die confidence mit der du sowas raushaust :D

2023-06-12 11:42 UTC, fhochleitner requested changes

2023-06-12 11:42 UTC, fhochleitner commented on infra/gp-grafana-instance/templates/grafana-crd.yaml
> +  resources:
ich würd mit 25-50 request cpu, 126mb ram reingehen und auf 100-150 cpu und 256 ram limitieren.

2023-06-12 12:19 UTC, Lucostus commented
> > @fhochleitner Ich habe das Gefühl, dass der Operator die Ressource Definition nicht übernimmt, wird vermutlich mit v5 gefixt sein.
> 
> hast du das nicht vorher mal ausprobiert/die die CRD angeschaut? resources sind unter .spec.containers[*].resources definiert. da wo sie aktuell stehen sind sie auch nicht zulässig, da wirft der operator das dann berechtigterweise raus. wobei ich mir nicht sicher bin, ob das die richtige stelle konfiguriert. probier das vielleicht vorher nochmal aus, bevor du es pusht?

In der CRD gibts ein Field für resources, an der Position wie es jetzt ist, und der Operator wirft es auch nicht raus, er deployt es nur nicht richtig. Wenn ich das unter container angeben würde, würd er einen neuen container im pod machen, soweit ich den Operator richtig verstanden habe

2023-06-12 12:29 UTC, fhochleitner commented
> > > @fhochleitner Ich habe das Gefühl, dass der Operator die Ressource Definition nicht übernimmt, wird vermutlich mit v5 gefixt sein.
> > 
> > 
> > hast du das nicht vorher mal ausprobiert/die die CRD angeschaut? resources sind unter .spec.containers[*].resources definiert. da wo sie aktuell stehen sind sie auch nicht zulässig, da wirft der operator das dann berechtigterweise raus. wobei ich mir nicht sicher bin, ob das die richtige stelle konfiguriert. probier das vielleicht vorher nochmal aus, bevor du es pusht?
> 
> In der CRD gibts ein Field für resources, an der Position wie es jetzt ist, und der Operator wirft es auch nicht raus, er deployt es nur nicht richtig. Wenn ich das unter container angeben würde, würd er einen neuen container im pod machen, soweit ich den Operator richtig verstanden habe.
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/41841989/245141257-d15395f6-4c91-4344-8c70-ae0cea6317ad.png">

da hab ich mich verschaut gehabt. aber die resources werden soweit ich das sehe ja eh übernommen: 
![image](https://github.com/gepaplexx/gp-helm-chart-development/assets/36953096/8df58bf4-0187-4e94-a1aa-dcd950b39de2)

2023-06-12 12:51 UTC, Lucostus commented
Ah, und ich habe immer die Request vom init Container angeschaut, whoops. Also Ressourcen funktionieren.

2023-06-13 10:43 UTC, fhochleitner approved these changes

2023-06-13 13:52 UTC, merged