Feature/gpx 597
gepaplexx/gp-helm-chart-development pull request #365
Opened 2023-06-22 15:11 UTC by ShahinMahmody

2023-06-23 06:06 UTC, fhochleitner requested changes

2023-06-23 06:06 UTC, fhochleitner commented on infra/gp-hashicorp-vault/helpers/vault-setup.sh
> +# BACKUP-TESTER
day-x-generator müsste schon angepasst worden sein. den teil bitte entsprechend dort hinzufügen.

2023-06-23 06:06 UTC, fhochleitner commented on infra/gp-hashicorp-vault/helpers/vault-setup.sh
> +      bound_service_account_namespaces=gp-cicd-eventbus \
kann man an der stelle mit wildcards arbeiten? darüber bin ich die letzten tage beim hinzufügen von der gitlab integration gestolpert. wäre schön, wenn hier nämespaces wie "*-cicd" funktioniert.

2023-06-23 06:06 UTC, fhochleitner commented on infra/gp-hashicorp-vault/templates/BackupCronJob.yaml
> +              image: 'hashicorp/vault:1.13.1'
bitte über templating lösen. bestenfalls kopplung an die version der vault selbst.

2023-06-23 06:06 UTC, fhochleitner commented on infra/gp-hashicorp-vault/templates/BackupTestJob.yaml
> +              image: 'hashicorp/vault:1.13.1'
image version und tag siehe vorige anmerkung

2023-06-27 10:14 UTC, tomeindl approved these changes

2023-06-28 12:50 UTC, ShahinMahmody commented on infra/gp-hashicorp-vault/helpers/vault-setup.sh
> +      bound_service_account_namespaces=gp-cicd-eventbus \
nein, bei sowas sollten wildcards nicht als Prä- oder Interfix funktionieren. Sollte auch so spezifisch wie möglich angegeben werden

2023-06-28 15:04 UTC, fhochleitner requested changes

2023-06-28 15:04 UTC, fhochleitner commented on infra/gp-hashicorp-vault/templates/BackupTestJob.yaml
> +    disable_mlock = true
das wirkt, wie wenn es ähnlich der config für die vault selbst in den values stehen?

2023-06-28 15:04 UTC, fhochleitner commented on infra/gp-hashicorp-vault/templates/BackupTestJob.yaml
> +                  memory: '100Mi'
values

2023-06-29 07:56 UTC, fhochleitner approved these changes

2023-06-29 12:59 UTC, merged