GPX-442
gepaplexx/gp-helm-chart-development pull request #91
Opened 2022-08-29 12:30 UTC by mario-oberwalder

2022-08-31 06:25 UTC, fhochleitner requested changes
Helm Chart Version bitte noch hochdrehen und die Änderung beim Alertnamen.

2022-08-31 06:25 UTC, fhochleitner commented on infra/gp-cluster-monitoring-config/templates/cluster-updating-prometheusrule.yaml
> +  - name: cluster-is-updating
Convention ist glaub ich, dass Alerts CamelCase Naming Scheme haben, soweit ich das bei allen Standard Alerts und von anderen Tools sehe. Würde hier (und unten bei "alert: ...") nicht mit der Convention brechen.

2022-09-01 06:48 UTC, fhochleitner requested changes
Helm Chart Version bitte noch hochdrehen und die Änderung beim Alertnamen.

2022-09-01 06:57 UTC, mario-oberwalder commented
version hochgezogen und gemerged, wie besprochen

2022-09-01 06:58 UTC, merged